services:
  backend:
    build: ./app
    container_name: backend-app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    env_file:
      - ./app/.env

  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: praktikum_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: